define("lodash/lang", ["lodash/lang/clone", "lodash/lang/cloneDeep", "lodash/lang/eq", "lodash/lang/gt", "lodash/lang/gte", "lodash/lang/isArguments", "lodash/lang/isArray", "lodash/lang/isBoolean", "lodash/lang/isDate", "lodash/lang/isElement", "lodash/lang/isEmpty", "lodash/lang/isEqual", "lodash/lang/isError", "lodash/lang/isFinite", "lodash/lang/isFunction", "lodash/lang/isMatch", "lodash/lang/isNaN", "lodash/lang/isNative", "lodash/lang/isNull", "lodash/lang/isNumber", "lodash/lang/isObject", "lodash/lang/isPlainObject", "lodash/lang/isRegExp", "lodash/lang/isString", "lodash/lang/isTypedArray", "lodash/lang/isUndefined", "lodash/lang/lt", "lodash/lang/lte", "lodash/lang/toArray", "lodash/lang/toPlainObject"], function(clone, cloneDeep, eq, gt, gte, isArguments, isArray, isBoolean, isDate, isElement, isEmpty, isEqual, isError, isFinite, isFunction, isMatch, isNaN, isNative, isNull, isNumber, isObject, isPlainObject, isRegExp, isString, isTypedArray, isUndefined, lt, lte, toArray, toPlainObject) {  return {
    'clone': clone,
    'cloneDeep': cloneDeep,
    'eq': eq,
    'gt': gt,
    'gte': gte,
    'isArguments': isArguments,
    'isArray': isArray,
    'isBoolean': isBoolean,
    'isDate': isDate,
    'isElement': isElement,
    'isEmpty': isEmpty,
    'isEqual': isEqual,
    'isError': isError,
    'isFinite': isFinite,
    'isFunction': isFunction,
    'isMatch': isMatch,
    'isNaN': isNaN,
    'isNative': isNative,
    'isNull': isNull,
    'isNumber': isNumber,
    'isObject': isObject,
    'isPlainObject': isPlainObject,
    'isRegExp': isRegExp,
    'isString': isString,
    'isTypedArray': isTypedArray,
    'isUndefined': isUndefined,
    'lt': lt,
    'lte': lte,
    'toArray': toArray,
    'toPlainObject': toPlainObject
  };
});
