define(["lodash/object"], ["lodash/object/assign", "lodash/object/create", "lodash/object/defaults", "lodash/object/extend", "lodash/object/findKey", "lodash/object/findLastKey", "lodash/object/forIn", "lodash/object/forInRight", "lodash/object/forOwn", "lodash/object/forOwnRight", "lodash/object/functions", "lodash/object/get", "lodash/object/has", "lodash/object/invert", "lodash/object/keys", "lodash/object/keysIn", "lodash/object/mapKeys", "lodash/object/mapValues", "lodash/object/merge", "lodash/object/methods", "lodash/object/omit", "lodash/object/pairs", "lodash/object/pick", "lodash/object/result", "lodash/object/set", "lodash/object/transform", "lodash/object/values", "lodash/object/valuesIn"], function(assign, create, defaults, extend, findKey, findLastKey, forIn, forInRight, forOwn, forOwnRight, functions, get, has, invert, keys, keysIn, mapKeys, mapValues, merge, methods, omit, pairs, pick, result, set, transform, values, valuesIn) {  return {
    'assign': assign,
    'create': create,
    'defaults': defaults,
    'extend': extend,
    'findKey': findKey,
    'findLastKey': findLastKey,
    'forIn': forIn,
    'forInRight': forInRight,
    'forOwn': forOwn,
    'forOwnRight': forOwnRight,
    'functions': functions,
    'get': get,
    'has': has,
    'invert': invert,
    'keys': keys,
    'keysIn': keysIn,
    'mapKeys': mapKeys,
    'mapValues': mapValues,
    'merge': merge,
    'methods': methods,
    'omit': omit,
    'pairs': pairs,
    'pick': pick,
    'result': result,
    'set': set,
    'transform': transform,
    'values': values,
    'valuesIn': valuesIn
  };
});
